### ISSUE TITLE
import SharedArray ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by HansYeoh** [dschinagl/occam#4]
Linux = Ubuntu 20.04 LTS
Python = 3.8
CUDA version = 11.3
PyTorch version = 1.10
spconv version =2.1.21

If I install version 1.23.0 of numpy, I get an error
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.56.0 requires numpy<1.23,>=1.18, but you have numpy 1.23.0 which is incompatible.
```

If I degrade the version of numpy to 1.22.4, I get another error
```
$ python occam_demo.py --ckpt demo_pcl.npy
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
Traceback (most recent call last):
  File "occam_demo.py", line 4, in <module>
    from pcdet.utils import common_utils
  File "/home/ubuntu/occam/pcdet/utils/common_utils.py", line 7, in <module>
    import SharedArray
ImportError: numpy.core.multiarray failed to import
```
```
$ python -c 'import SharedArray'
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: numpy.core.multiarray failed to import
```

**Comment by dschinagl** [comment]
Hi,

according to a similar `OpenPCDet` issue, a pip upgrade before installing the packages should solve the problem:
`pip install --upgrade pip`

Alternatively you can use an older sharedarray version:
 **sharedarray==3.1.0**
 
Best,
David

**Comment by HansYeoh** [comment]
"use an older sharedarray version" works fine,Thank you for you reply.
Best wishes.
